### PR TITLE
Add test for bad substitution that works in bash

### PR DESCRIPTION
**Pull request by mmlb**
Just a quick PR to run the test and see if it fails.

### CODE REVIEW

**Comment by mmlb** [comment]
how is this test passing @bradrydzewski ? The introduced `fmt.Println` should have failed to compile.
```
envsubst / 591ms
❯ go test                                                                                                 patch-1
# github.com/drone/envsubst
./eval_test.go:183:3: undefined: fmt
FAIL    github.com/drone/envsubst [build failed]```

**Comment by mmlb** [comment]
wow now I'm very much confused:
```
❯ go test                                                                                                 patch-1
# github.com/drone/envsubst
./eval_test.go:183:3: undefined: fmt
FAIL    github.com/drone/envsubst [build failed]
envsubst /
❯ go test -v ./...                                                                                        patch-1
# github.com/drone/envsubst
./eval_test.go:183:3: undefined: fmt
FAIL    github.com/drone/envsubst [build failed]
=== RUN   TestParse
--- PASS: TestParse (0.00s)
PASS
ok      github.com/drone/envsubst/parse 0.002s
```

**Comment by mmlb** [comment]
ok sorry, so `go test` still errors out due to failed to build tests for github.com/drone/subst, but the error is ignored due to pipefail not being set and `| tee gotest.out` not erroring. I'm going to update the .drone.yml file so that this errors as expected.

**Comment by bradrydzewski** [comment]
I updated the yaml to remove the tee command, which was no longer required.

> Just a quick PR to run the test and see if it fails.

Let's not do this. I get notifications for pull requests and would ask that you clone the code locally to test your changes. Thanks!

**Comment by mmlb** [comment]
Apologies for the extra noise, I'm getting bad substitution on `py${PYTHON_VERSION/./}` (I'll take to discourse though) and figured a PR showing a failed test is somewhat better than just an issue. Good intentions...

**Comment by bradrydzewski** [comment]
The error in this pull request was caused by `fmt` not being imported. The substitution string in your unit test will pass.

```diff
+		{
+			params: map[string]string{"stringZ": "foo.bar"},
+			input:  `py${stringZ/./-}`,
+			output: "pyfoo-bar",
+		},
```

**Pull request closed without merging**
