### PR TITLE
Escape dollar sign

### PR DESCRIPTION
**Pull request by execjosh**
As per #2, support `$$`.

### CODE REVIEW

**Comment by jmccann** [comment]
LGTM

Thoughts @bradrydzewski ?

**Comment by bradrydzewski** [comment]
LGTM thanks!

**Comment by bradrydzewski** [comment]
note that I will need to update the vendored dependency in drone/drone for this to take effect. I plan on doing so tomorrow

**Comment by execjosh** [comment]
Great!  Glad I could help 😄

**Pull request merged**
